application: wiki
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: .*
  script: wiki.app

- url: /Static/css
  static_dir: css
- url: /Static/img
  static_dir: img
- url: /Static/js
  static_dir: js

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
